name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest version of the code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.70.0
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - name: Calculator tests
        run: bundle exec ./run test
        env:
          MINITEST_REPORTER: JUnitReporter

      - name: Report tests
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test/reports/*.xml

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout the whole repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      - name: Push to Heroku
        run: git push -f heroku main:main
